gcloud functions deploy func-publisher-golang \
    --gen2 \
    --runtime=go122 \
    --project=bullla-one-d-apps-cn-92c3 \
    --region=us-central1 \
    --source=./bullla-functions/publisher/ \
    --entry-point=Main \
    --trigger-http \
    --timeout=300s \
    --cpu=1 \
    --memory=256M \
    --vpc-connector=projects/gc-pr-host-dev/locations/us-central1/connectors/conn-serverless-dev \
    --egress-settings=private-ranges-only \
    --service-account=gcp-functions@bullla-one-d-apps-cn-92c3.iam.gserviceaccount.com \
    --env-vars-file=./env-vars-func1.yaml